version: "3.8"

services:
  mysql:
    image: "mysql:8.0"
    volumes:
      - data:/var/lib/mysql
    environment:
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3309:3306"
    # env_file:
    #   - ./mysql.env
    # networks:
    #   - new_app

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=staging
        - APP_PORT=4002
    # image: mbaba317468/golangwebserver:latest
    ports:
      - 4002:4002
    environment:
      - APP_ENV=staging
      - APP_PORT=4002
    env_file:
      - ./.env.local
    volumes:
      - logs:/root/gin.log #named volume
      - ./:/app #bind volume
      # - /app/node_modules # anonymous volume
    depends_on:
      - mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080 
    depends_on:
      - mysql


volumes:
  data:
  logs:
