# POST http://backend:4000/events
POST http://localhost:4001/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MDY1MzkzMjIsImlkIjoxfQ.8yg8ia4G4G4kCjbNkcf8aHvXhA32K2ebUlPR507fou8

{
  "name": "Programming hackathon 2",
  "description": "Price distribution after config the jwt complete process",
  "location": "Bhopal"
}

