POST http://localhost:4000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3MDM2MDIzMDcsImlkIjoxfQ.YC9IgwLLDsTsLNsTryQL_mtQPfg28ccwqtYiML31QfY

{
  "name": "Programming hackathon4",
  "description": "eePrice distribution after config the jwt complete process",
  "location": "Bhopal"
}

